services:
  airflow:
    image: apache/airflow:2.8.0
    container_name: airflow
    command: standalone
    volumes:
      - ./airflow-dags:/opt/airflow/dags
    ports:
      - 8081:8080

  postgre:
    image: postgres:13
    container_name: postgre
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - 5431:5432







